- name: Install Python and tools
  apt:
    name: [python3-pip, python3-venv]
    state: present
    update_cache: yes

- name: Create app directory
  file:
    path: /home/ubuntu/flaskapp
    state: directory

- name: Copy Flask app and requirements
  copy:
    src: "{{ item }}"
    dest: /home/ubuntu/flaskapp/
  with_items:
    - app.py
    - requirements.txt

- name: Create virtual environment
  command: python3 -m venv venv
  args:
    chdir: /home/ubuntu/flaskapp

- name: Install dependencies
  shell: bash -c "source venv/bin/activate && pip install -r requirements.txt"
  args:
    chdir: /home/ubuntu/flaskapp

- name: Add systemd service file
  template:
    src: flask.service.j2
    dest: /etc/systemd/system/flask.service

- name: Start and enable Flask service
  systemd:
    name: flask
    enabled: yes
    state: started
    daemon_reload: yes

